### ISSUE TITLE
The "extensions.cookie-restrictions.wasEnabled" pref wrongly remains displayed in the "about:config" page after the add-on was removed

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/CookieRestrictionsShield#89] opened 2018-09-14 12:12 UTC
**[Affected versions]:**
- Firefox 63.0b6

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a Firefox profile with the following prefs in the "about:config" page:
	- "shieldStudy.logLevel" with "All" value;
	- "extensions.cookie-restrictions_shield_mozilla_org.test.variationName" with "CookiesBlocked" value.
- Have the latest "Cookie Restrictions".xpi installed from [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1485518).

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:addons>Extensions" and remove the "Mozilla Cookie Restrictions User Study".
3. Go to the "about:config" page and search for "cookie-restrictions" related prefs.
4. Observe the results.

**[Expected result]:**
- There is no pref displayed for this query.

**[Actual result]:**
- The ""extensions.cookie-restrictions.wasEnabled"" pref is displayed.

**[Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/45549366-40ce4100-b830-11e8-88bf-e27d995c4464.gif)

**Comment by ericawright** [comment] 2018-09-14 14:48
this is as designed. the pref `extensions.cookie-restrictions.wasEnabled` is left behind to be used for surveying the users after the experiment ends

**Comment by TanviHacks** [comment] 2018-09-14 16:20
Closing this as this is intended behavior.

**Closed by TanviHacks** 2018-09-14 16:20 UTC
